# Generated by Django 4.2.7 on 2023-11-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
